SELECT
  YEAR(
    DATE(
      VARCHAR('20' || SUBSTR(CHAR(MMRHQLIB.SODHDR.OHSTDT),1,2) || '-' ||
              SUBSTR(CHAR(MMRHQLIB.SODHDR.OHSTDT),3,2) || '-' ||
              SUBSTR(CHAR(MMRHQLIB.SODHDR.OHSTDT),5,2))
    )
  ) AS Order_Year,
 
  WEEK(
    DATE(
      VARCHAR('20' || SUBSTR(CHAR(MMRHQLIB.SODHDR.OHSTDT),1,2) || '-' ||
              SUBSTR(CHAR(MMRHQLIB.SODHDR.OHSTDT),3,2) || '-' ||
              SUBSTR(CHAR(MMRHQLIB.SODHDR.OHSTDT),5,2))
    )
  ) AS Order_Week,

  MMRHQLIB.SODHDR.OHSHLO AS Shipping_Location,

  COUNT(DISTINCT MMRHQLIB.SODSHD.SDOHNO) AS Number_of_Orders,
  COUNT(DISTINCT MMRHQLIB.SODSHD.SDSKU) AS Number_of_Distinct_SKUs,
  SUM(MMRHQLIB.SODSHD.SDSPQT) AS Total_Units_Shipped,
  SUM(MMRHQLIB.SODSHD.SDEXPR) AS Total_Extended_Price_Shipped

FROM
  ((MMRHQLIB.SODSHH
    INNER JOIN MMRHQLIB.SODSHD ON MMRHQLIB.SODSHH.SHOHNO = MMRHQLIB.SODSHD.SDOHNO)
   INNER JOIN MMRHQLIB.SODHDR ON (MMRHQLIB.SODSHD.SDOHNO = MMRHQLIB.SODHDR.OHOHNO)
                            AND (MMRHQLIB.SODSHD.SDSLLN = MMRHQLIB.SODHDR.OHSLLO))
   INNER JOIN MMRHQLIB.SODADR ON (MMRHQLIB.SODSHD.SDOHNO = MMRHQLIB.SODADR.OAOHNO)
                            AND (MMRHQLIB.SODSHD.SDSLLN = MMRHQLIB.SODADR.OASLLO)

WHERE
  MMRHQLIB.SODHDR.OHSTDT > 240105
  AND MMRHQLIB.SODSHD.SDEXPR NOT IN (0)
  AND MMRHQLIB.SODHDR.OHSHLO IN (44100, 43060, 44280)
  AND MMRHQLIB.SODHDR.OHDPMT IN ('D', 'S', 'T')

GROUP BY
  YEAR(
    DATE(
      VARCHAR('20' || SUBSTR(CHAR(MMRHQLIB.SODHDR.OHSTDT),1,2) || '-' ||
              SUBSTR(CHAR(MMRHQLIB.SODHDR.OHSTDT),3,2) || '-' ||
              SUBSTR(CHAR(MMRHQLIB.SODHDR.OHSTDT),5,2))
    )
  ),
  WEEK(
    DATE(
      VARCHAR('20' || SUBSTR(CHAR(MMRHQLIB.SODHDR.OHSTDT),1,2) || '-' ||
              SUBSTR(CHAR(MMRHQLIB.SODHDR.OHSTDT),3,2) || '-' ||
              SUBSTR(CHAR(MMRHQLIB.SODHDR.OHSTDT),5,2))
    )
  ),
  MMRHQLIB.SODHDR.OHSHLO

ORDER BY
  Order_Year,
  Order_Week,
  Shipping_Location
